/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'z003dv0s' at '12/9/16 9:45 AM' with Gradle 3.0
 *
 * @author z003dv0s, @date 12/9/16 9:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
